version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: nest_colyseus_mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: nestcolyseus
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'

volumes:
  mongo_data:
